better -u logic

diff --git a/azule b/azule
--- a/azule
+++ b/azule
@@ -1,30 +1,34 @@
 #!/bin/zsh
 
 # ARGUEMENTS
-while getopts :n:i:o:f:d:h args; do
+while getopts :n:i:o:f:d:h:u args; do
     case "$args" in
-        n) name="$OPTARG"
+        n)
+            name="$OPTARG"
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
                 name+=" $(eval "echo \${$OPTIND}")"
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
-        i) ipadir="$OPTARG"
+        i)
+            ipadir="$OPTARG"
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
                 ipadir+=" $(eval "echo \${$OPTIND}")"
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
-        o) outdir="$OPTARG"
+        o)
+            outdir="$OPTARG"
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
                 outdir+=" $(eval "echo \${$OPTIND}")"
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
-        f) ff="$OPTARG"
+        f)
+            ff="$OPTARG"
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
                 ff+=" "$(eval "echo \${$OPTIND}")""
                 OPTIND=$((OPTIND + 1))
@@ -32,13 +36,16 @@ while getopts :n:i:o:f:d:h args; do
             IFS=$'\n' files=( $(eval "echo $ff" | sed "s/, /\n/g") )
             ;;
             
-        d) dylibs=("$OPTARG")
+        d)
+            dylibs=("$OPTARG")
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
                 dylibs+=($(eval "echo \${$OPTIND}"))
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
+        u) u=1 ;;
+        
         h)
             echo "Usage: azule [options]"
             echo
@@ -71,15 +78,8 @@ while getopts :n:i:o:f:d:h args; do
             ;;
         *)
             # SWITCHES
-            while getopts ":u" args; do
-                case "$args" in
-                    u) switches+=u ;;
-                esac
-            done
-            if [ "$switches" = "null" ]; then
-                echo 'Invalid argument. Run "azule -h" to print the help menu.'
-                exit 1
-            fi
+            echo 'Invalid argument. Run "azule -h" to print the help menu.'
+            exit 1
             ;;
     esac
 done
@@ -205,7 +205,7 @@ for i in "${chain[@]}"; do
     done
 done
 
-if [[ "$switches" =~ "u" ]]; then
+if [ -z "$u" ]; then
     plutil -remove UISupportedDevices Payload/*.app/Info.plist >> /dev/null
 fi
 
