-w for removing watch app

diff --git a/azule b/azule
--- a/azule
+++ b/azule
@@ -158,7 +158,7 @@ cleanup () {
 }
 
 # CLI ARGUEMENTS
-while getopts :n:i:o:c:a:b:x:f:d:p:huSmelv args; do
+while getopts :n:i:o:c:a:b:x:f:d:p:huSmewlv args; do
     case "$args" in
         n)
             name="$OPTARG"
@@ -257,6 +257,7 @@ while getopts :n:i:o:c:a:b:x:f:d:p:huSmelv args; do
         ;;
         
         e) e=1 && run=1 ;;
+        w) w=1 && run=1 ;;
         l) l=1 ;;
         S) fakesign=1 && run=1 ;;
                 
@@ -279,8 +280,9 @@ while getopts :n:i:o:c:a:b:x:f:d:p:huSmelv args; do
             echo "  -m                           Enables the manual dylib selection 'UI' (Not Recommended)"
             echo "  -S                           Fakesigns iPA for use with AppSync"
             echo "  -e                           Removes App Extensions"
+            echo "  -w                           Removes Watch App"
             echo "  -x [Apple ID] [Password]     Fetch and decrypt iPA [iOS Only]"
-            echo "  -l                           Bypass Updating Outdated Apps"
+            echo "  -l                           Don't Update Outdated Apps"
             echo "  -h                           Print this help menu"
             echo
             echo "Examples:"
@@ -324,11 +326,11 @@ if [ ! -f "$ipadir" ] && [ "$os" == "iOS" ]; then
         echo "Invalid App"
         exit 1
     fi
-    run=1
+    drun=1
 fi
 
 # GUI
-if [ -z $run ]; then
+if [[ -z "$run" && -z "$drun" ]]; then
     PS3=$'Choose Arguements: '
     arguements=(
     "Inject Tweaks"
@@ -338,17 +340,18 @@ if [ -z $run ]; then
     "Remove UISupportedDevices"
     "Fakesign iPA"
     "Remove App Extensions"
+    "Remove Watch App"
     "Run With Verbose Mode"
     "Set Custom Output Name"
     "Manually Inject dylib files (Not Recommended)"
     "Use APT instead of Parcility"
-    "Done"
     )
     
     if [ "$os" == "iOS" ]; then
         arguements+=( "Do Not Update Outdated Apps" )
     fi
     
+    arguements+=( "Done" )
     select i in "${arguements[@]}"; do
         case "$i" in
             "Inject Tweaks")
@@ -424,6 +427,11 @@ if [ -z $run ]; then
             "Manually Inject dylib files (Not Recommended)") m=1 ;;
             "Run With Verbose Mode") v="-v" ;;
             
+            "Remove Watch App")
+                w=1
+                run=1
+            ;;
+            
             "Remove App Extensions")
                 e=1
                 run=1
@@ -436,7 +444,7 @@ fi
 
 # VARIABLE CHECK
 
-if [ -z "$run" ]; then
+if ! [[ -n "$run" || -n "$drun" ]]; then
     echo "Insufficient Arguements"
     echo "Run "azule -h" for usage instructions"
     exit 1
@@ -503,7 +511,7 @@ cd "$dir/$tweakid"
 
 # DECRYPTION
 
-if [ ! -f "$ipadir" ] && [ "$os" == "iOS" ]; then
+if [ -n "$drun" ]; then
 
     # BFDECRYPT
     
@@ -518,9 +526,7 @@ if [ ! -f "$ipadir" ] && [ "$os" == "iOS" ]; then
     
     currentv="$(ExtractPlistValue CFBundleVersion "$bfplist")"
     
-    if [ -n "$currentv" ]; then
-        l+=1
-    fi
+    if [ -n "$currentv" ]; then l+=1; fi
     
     # INSTALL UPDATES
     if [[ "$latestv" != "$currentv" && "$l" != "11" ]]; then
@@ -600,39 +606,52 @@ fi
 
 # EXTRACTING IPA
 
-echo "Extracting iPA..."
-eval "unzip -q '$ipadir' -d $dir/'$tweakid'"
-Verbose "IPA extracted" "Couldn't extract IPA"
-rm -rf "$bfipadir"
+if [ -n "$run" ]; then
+    echo "Extracting iPA..."
+    eval "unzip -q '$ipadir' -d $dir/'$tweakid'"
+    Verbose "IPA extracted" "Couldn't extract IPA"
+    rm -rf "$bfipadir"
+fi
 
 # REMOVING PLUGINS
 
 if [ -n "$e" ]; then
     echo "Removing Extensions..."
-    rm -rf Payload/*.app/Plug*ns
+    find "$dir/$tweakid" -type d -mindepth 3 -maxdepth 3 -name PlugIns -exec rm -rf "{}" \;
     Verbose "Removed Extensions" "Couldn't Remove Extensions"
 fi
 
-# SETTING APP EXECUTABLE
+# REMOVING WATCH APP
 
-executable="Payload/$(basename Payload/*.app)/$(ExtractPlistValue CFBundleExecutable Payload/*.app/Info.plist)"
-Verbose "App executable is $executable" "Couldn't set app executable" -v
-    
-# ENCRYPTION CHECK
+if [ -n "$w" ]; then
+    echo "Removing Watch App..."
+    find "$dir/$tweakid" -type d -mindepth 3 -maxdepth 3 -name Watch -exec rm -rf "{}" \;
+    Verbose "Removed Watch App" "Couldn't Remove Watch App"
+fi
 
-for i in $(find Payload/*.app -name "Info.plist" ); do
-    CFBundleExecutable="$(ExtractPlistValue CFBundleExecutable "$i")"
-    if [[ -n "$CFBundleExecutable" && "$("$otool" -l "$(dirname "$i")/$CFBundleExecutable" | grep "cryptid 1")" ]]; then
-        if ! [[ "$(dirname "$i")/$CFBundleExecutable" =~ ".app/PlugIns" ]]; then
-            echo "Fatal Error: "$(dirname "$i")/$CFBundleExecutable" is encrypted"
-            exit 1
-        else
-            if [ -n "$v" ]; then
-                echo ""$(dirname "$i")/$CFBundleExecutable" is encrypted. This may cause problems later on"
+if [ -n "$run" ]; then
+
+    # SETTING APP EXECUTABLE
+
+    executable="Payload/$(basename Payload/*.app)/$(ExtractPlistValue CFBundleExecutable Payload/*.app/Info.plist)"
+    Verbose "App executable is $executable" "Couldn't set app executable" -v
+
+    # ENCRYPTION CHECK
+
+    for i in $(find Payload/*.app -name "Info.plist" ); do
+        CFBundleExecutable="$(ExtractPlistValue CFBundleExecutable "$i")"
+        if [[ -n "$CFBundleExecutable" && "$("$otool" -l "$(dirname "$i")/$CFBundleExecutable" | grep "cryptid 1")" ]]; then
+            if ! [[ "$(dirname "$i")/$CFBundleExecutable" =~ ".app/PlugIns" ]]; then
+                echo "Fatal Error: "$(dirname "$i")/$CFBundleExecutable" is encrypted"
+                exit 1
+            else
+                if [ -n "$v" ]; then
+                    echo ""$(dirname "$i")/$CFBundleExecutable" is encrypted. This may cause problems later on"
+                fi
             fi
         fi
-    fi
-done
+    done
+fi
 
 # PROCESSING FILES
 
@@ -850,6 +869,12 @@ fi
 
 # WRAPPING UP
 
-echo "Generating iPA..."
-eval "zip -rq '$output' Payload"
+if [ -n "$run" ]; then
+    echo "Generating iPA..."
+    eval "zip -rq '$output' Payload"
+else
+    mv "$ipadir" "$output"
+fi
 Verbose "Generated IPA at $output" "Couldn't generate IPA"
+
+cleanup
