..uh.. a fucking lot

diff --git a/azule b/azule
--- a/azule
+++ b/azule
@@ -1,7 +1,10 @@
 #!/bin/zsh
 
+# CLEAN ON EXIT
+trap "rm -rf $AZULE/.tmp && exit" SIGINT
+
 # ARGUEMENTS
-while getopts :n:i:o:v:f:d:hu args; do
+while getopts :n:i:o:c:f:d:humv args; do
     case "$args" in
         n)
             name="$OPTARG"
@@ -27,58 +30,61 @@ while getopts :n:i:o:v:f:d:hu args; do
             done
             ;;
             
-        v)
-            v="$OPTARG"
+        c)
+            c="$OPTARG"
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
-                v+=" $(eval "echo \${$OPTIND}")"
+                c+=" $(eval "echo \${$OPTIND}")"
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
         f)
-            ff="$OPTARG"
+            files=("$OPTARG")
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
-                ff+=" "$(eval "echo \${$OPTIND}")""
+                files+=($(eval "echo \${$OPTIND}"))
                 OPTIND=$((OPTIND + 1))
             done
-            (){ local IFS=$'\n'; files=( $(eval "echo $ff" | sed "s/, /\n/g") ); }
             ;;
             
         d)
-            dylibs=("$OPTARG")
+            inject=("$OPTARG")
             until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
-                dylibs+=($(eval "echo \${$OPTIND}"))
+                inject+=($(eval "echo \${$OPTIND}"))
                 OPTIND=$((OPTIND + 1))
             done
             ;;
             
         u) u=1 ;;
         
+        v) v=1 ;;
+        
+        m) m=1 ;;
+                
         h)
             echo "Usage: azule [options]"
             echo
-            echo "Running the command without any arguments will enter GUI mode."
+            echo "Running the command without any arguments will enter 'GUI' mode"
             echo
             echo "GUI mode usage: "
             echo "  1. Run azule in any terminal window to initialize"
-            echo "  2. Provide your project's name"
-            echo "  3. Provide the path to a \u001b[1mdecrypted\u001b[0m IPA of the app you are trying to modify."
+            echo "  2. Provide the path to a \u001b[1mdecrypted\u001b[0m IPA of the app you are trying to modify."
             echo "  \u001b[1mEncrypted IPAs don't work\u001b[0m"
-            echo "  4. When asked for Files or Tweak Bundle IDs, you can either provide the local"
+            echo "  3. When asked for Files or Tweak Bundle IDs, you can either provide the local"
             echo "  paths to the files you wish to inject or type the Bundle IDs of the tweaks"
             echo "  (This only works if the tweaks can be found on Parcility)"
-            echo "  5. If you provided a tweak, choose the dylibs to inject"
-            echo "  (You can choose not to inject any dylibs)"
+            echo "  4. If you provided a tweak, choose the tweak files to inject"
             echo
             echo "Options:"
-            echo "  -n [Name]                Specify the project name."
-            echo "  -i [Path]                Specify the path to the IPA to patch."
-            echo "  -o [Path]                Specify an output directory."
-            echo "  -f [Paths/Bundle IDs]    Specify the files or tweak Bundle IDs to import."
-            echo "  -d [Names]               From the .deb files imported, specify the names of the dylibs (e.g: Foo.dylib) to inject."
-            echo "  -v [Version]             Set custom version for output ipa"
-            echo "  -h                       Print this help menu."
+            echo "  -n [Name]                Specify an Output Name"
+            echo "  -i [Path]                Specify the path to the IPA to patch"
+            echo "  -o [Path]                Specify an output directory"
+            echo "  -f [Paths/Bundle IDs]    Specify the files or tweak Bundle IDs to import"
+            echo "  -d [Names]               From the .deb files imported, specify the names of the dylibs (e.g: Foo.dylib) to inject"
+            echo "  -c [Version]             Set custom version for output ipa"
+            echo "  -h                       Print this help menu"
             echo "  -u                       Remove UISupportedDevices from Info.plist"
+            echo "  -v                       Enable Verbose Mode"
+            echo "  -m                       Enables the manual dylib selection 'UI'"
             echo
             echo "Examples:"
             echo "  azule -n Foo -i ~/Foo.ipa -o ~/Foo/ -f ~/Foo.dylib, ~/Foo.bundle"
@@ -93,13 +99,6 @@ while getopts :n:i:o:v:f:d:hu args; do
     esac
 done
 
-# DECLARE $NAME
-if [ -z "$name" ]; then; while
-    printf 'Project Name: '
-    read name
-    [ -z "$name" ] && echo "Nice try. Now name your project."
-do true; done; fi
-
 # GET IPA
 if [ -z "$ipadir" ]; then; while
     printf 'Path to IPA: '
@@ -107,6 +106,47 @@ if [ -z "$ipadir" ]; then; while
     ipadir=$(eval "echo \$ipa")
     [ -z "$ipadir" ] && echo "I need the IPA to make your app."
 do true; done; fi
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ -f "$ipadir" ]; then
+        echo "Path to IPA is $ipadir"
+    else
+        echo "Invalid Path to IPA"
+    fi
+fi
+
+# GET FILES
+if [ -z "$files" ]; then; while
+    printf 'Files or Tweak IDs: '
+    read ff
+    files=( $(eval "echo $ff") )
+    [ -z "$files" ] && echo "If you don't want to inject anything, then just use the IPA you gave me."
+do true; done; fi
+
+# VERBOSE
+if [ -f "$v" ]; then
+    for i in "${files[@]}"; do
+        echo "$i will be imported"
+    done
+fi
+
+# DECLARE $NAME
+if [ -z "$name" ]; then
+    name="$(basename "$ipadir")"
+    for i in "${files[@]}"; do
+        name+="+"$(basename "$i")""
+    done
+fi
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ -n "$name" ]; then
+        echo "Output Name is $name"
+    else
+        echo "Invalid Output Name"
+    fi
+fi
 
 # OUTPUT DIRECTORY
 if [ -z "$outdir" ]; then; while
@@ -116,28 +156,48 @@ if [ -z "$outdir" ]; then; while
     [ -z "$outdir" ] && echo "I don't want to keep the app for myself."
 do true; done; fi
 
-# GET FILES
-if [ -z "$files" ]; then; while
-    printf 'Files or Tweak IDs: '
-    read ff
-    (){ local IFS=$'\n'; files=( $(eval "echo $ff" | sed "s/, /\n/g") ); }
-    [ -z "$files" ] && echo "If you don't want to inject anything, then just use the IPA you gave me."
-do true; done; fi
-
-# OUTPUT DIRECTORY #2
 tweakname=$(basename "$name")
 output=$(echo "$outdir/$name" | sed "s/"$tweakname"//g")
-if ! [[ -d "$output" ]]; then
+if [ ! -d "$output" ]; then
     mkdir -p "$output"
+fi
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ -d "$output" ]; then
+        echo "Output Directory is $output"
+    else
+        echo "Invalid Output Directory"
+    fi
 fi
 
 # .TMP DIRECTORIES
 dir=$AZULE/.tmp
 mkdir -p "$dir/$tweakname/Tweak"
+mkdir -p "$dir/$tweakname/Custom"
 cd "$dir/$tweakname"
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [[ -d "$dir/$tweakname/Tweak" && -d "$dir/$tweakname/Custom" ]]; then
+        echo "Work directory has been created"
+    else
+        echo "Couldn't create work directory"
+    fi
+fi
 
 # EXTRACT IPA
 eval "unzip -q '$ipadir' -d "$dir/'$tweakname'""
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ -d "$dir/$tweakname/Payload" ]; then
+        echo "IPA extracted"
+    else
+        echo "Couldn't extract IPA"
+    fi
+fi
+
 executable="Payload/$(basename Payload/*.app)/$(plutil -extract CFBundleExecutable xml1 -o - Payload/*.app/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")"
 
 for i in "${files[@]}"; do
@@ -148,30 +208,90 @@ for i in "${files[@]}"; do
             cd ar
             ar -x "$i"
             tar -C "$dir/$tweakname/Tweak" -xf data.tar.*
+            
+            # VERBOSE
+            if [ -n "$v" ]; then
+                if [ $? = 0 ]; then
+                    echo "$(basename "$i") extracted"
+                else
+                    echo "Failed to extract $(basename "$i")"
+                fi
+            fi
+            
             cd "$dir/$tweakname"
             rm -rf ar
             ;;
             
             *.dylib)
-                rsync -a "$i" Payload/*.app/Frameworks
-                $AZULE/bin/insert_dylib --inplace --all-yes "@rpath/$(basename "$i")" "$executable" >> /dev/null
-                chain+=( $(basename "$i") )
+                rsync -a "$i" "$dir/$tweakname/Custom"
+                
+                # VERBOSE
+                if [ -n "$v" ]; then
+                    if [ $? = 0 ]; then
+                        echo "Copied "$i" to work directory"
+                    else
+                        echo "$i couldn't be copied to work directory"
+                    fi
+                fi
+                
+                inject+=( $(basename "$i") )
                 ;;
 
             *.framework)
                 rsync -a "$i" Payload/*.app/Frameworks
-                chain+=( "$(basename "$i")/$(plutil -extract CFBundleExecutable xml1 -o - "$i"/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")" )
+                
+                # VERBOSE
+                if [ -n "$v" ]; then
+                    if [ $? = 0 ]; then
+                        echo "Copied "$i" to work directory"
+                    else
+                        echo "$i couldn't be copied to work directory"
+                    fi
+                fi
+                
+                inject+=( "$(basename "$i")/$(plutil -extract CFBundleExecutable xml1 -o - "$i"/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")" )
+                
                 ;;
             
-            *) rsync -a "$i" Payload/*.app ;;
+            *) rsync -a "$i" Payload/*.app
+            
+                # VERBOSE
+                if [ -n "$v" ]; then
+                    if [ $? = 0 ]; then
+                        echo "Copied "$i" to work directory"
+                    else
+                        echo "$i couldn't be copied to work directory"
+                    fi
+                fi
+                ;;
         esac
     else
         if [ "$(curl -sS https://api.parcility.co/db/package/"$i" | $AZULE/bin/jq -r .status)" = "true" ]; then
             mkdir -p ar
             cd ar
             curl -sSL "$(curl -sS https://api.parcility.co/db/package/$i | $AZULE/bin/jq -r '.data.repo.url + .data.builds[-1].Filename')" -o "$i.deb"
+            
+            # VERBOSE
+            if [ -n "$v" ]; then
+                if [ -f "$i.deb" ]; then
+                    echo "Fetched "$i""
+                else
+                    echo "Couldn't fetch $i"
+                fi
+            fi
+            
             ar -x "$i.deb"
             tar -C "$dir/$tweakname/Tweak" -xf data.tar.*
+            
+            # VERBOSE
+            if [ -n "$v" ]; then
+                if [ $? = 0 ]; then
+                    echo "$(basename "$i") extracted"
+                else
+                    echo "Failed to extract $(basename "$i")"
+                fi
+            fi
+            
             cd "$dir/$tweakname"
             rm -rf ar
         else
@@ -182,7 +302,7 @@ for i in "${files[@]}"; do
 done
 
 # SPECIFY DYLIBS
-if [ -z "$dylibs" ]; then
+if [ -n "$m" ]; then
     if [ -n "$(ls -A "$dir"/"$tweakname"/Tweak 2>/dev/null)" ]; then
         export COLUMNS=1
         dylibs=( $(find -E "$dir"/"$tweakname"/Tweak -iname '*.dylib' -exec basename {} \;) 'Done' )
@@ -191,55 +311,172 @@ if [ -z "$dylibs" ]; then
         select i in "${dylibs[@]}"; do
             if [ "$i" = "Done" ]; then; break
             else
-                find -E "$dir"/"$tweakname"/Tweak -iname "$i" -exec rsync -a {} Payload/*.app/Frameworks \;
-                $AZULE/bin/insert_dylib --inplace --all-yes "@rpath/$i" "$executable" >> /dev/null
-                chain+=( "$i" )
+                inject+=( "$i" )
             fi
         done
+    else
+        echo "No dylibs available"
+        pause
     fi
 else
+    dylibs=( $(find -E "$dir"/"$tweakname"/Tweak -iname '*.dylib') )
+
     for i in "${dylibs[@]}"; do
-        find -E "$dir"/"$tweakname"/Tweak -iname "$i" -exec rsync -a {} "$dir"/"$tweakname"/Payload/*.app/Frameworks \;
-        $AZULE/bin/insert_dylib --inplace --all-yes "@rpath/$i" "$executable" >> /dev/null
-        chain+=( "$i" )
+        bundles="$(plutil -extract Filter xml1 -o - "${i%.*}.plist" | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")"
+        ipabundleid="$(plutil -extract CFBundleIdentifier xml1 -o - Payload/*.app/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")"
+    
+        if [[ "$bundles" =~ "$ipabundleid" ]]; then
+            inject+=( "$(basename "$i")" )
+        fi
     done
 fi
 
+for i in "${inject[@]}"; do
+    find -E "$dir/$tweakname/Tweak" "$dir/$tweakname/Custom" -iname "$i" -exec rsync -a {} Payload/*.app/Frameworks \;
+    $AZULE/bin/insert_dylib --inplace --all-yes "@rpath/$i" "$executable" >> /dev/null
+    
+    # VERBOSE
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Injected $i"
+        else
+            echo "Couldn't inject $i)"
+        fi
+    fi
+done
+
 # MOVE BUNDLES
-find -E "$dir"/"$tweakname"/Tweak -iname '*.bundle' ! -iregex '.*\.(bundle)/.+' -exec rsync -a {} Payload/*.app \;
+find -E "$dir/$tweakname/Tweak" -iname '*.bundle' ! -iregex '.*\.(bundle)/.+' | while read i; do
+    rsync -a "$i" Payload/*.app \;
+    
+    # VERBOSE
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Copied "$(basename "$i")" to app directory"
+        else
+            echo ""$(basename "$i")" couldn't be copied to app directory"
+        fi
+    fi
+done
 
 # FIX LINKS
 rsync -a $AZULE/CydiaSubstrate.framework Payload/*.app/Frameworks
-chain+=( CydiaSubstrate.framework/CydiaSubstrate )
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ $? = 0 ]; then
+        echo "Copied CydiaSubstrate.framework to app directory"
+    else
+        echo "CydiaSubstrate.framework couldn't be copied to app directory"
+    fi
+fi
+    
+inject+=( CydiaSubstrate.framework/CydiaSubstrate )
 
 find -E "$dir/$tweakname/Tweak" -iname '*.framework' | while read i; do
     rsync -a "$i" Payload/*.app/Frameworks
     
-    chain+=( "$(basename "$i")/$(plutil -extract CFBundleExecutable xml1 -o - "$i"/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")" )
+    # VERBOSE
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Copied $(basename "$i") to app directory"
+        else
+            echo "$(basename "$i") couldn't be copied to app directory"
+        fi
+    fi
+    
+    inject+=( "$(basename "$i")/$(plutil -extract CFBundleExecutable xml1 -o - "$i"/Info.plist | sed -n "s/.*<string>\(.*\)<\/string>.*/\1/p")" )
 done
 
-for i in "${chain[@]}"; do
+for i in "${inject[@]}"; do
     codesign --remove-signature Payload/*.app/Frameworks/"$i"
+    
+    # VERBOSE ~~
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Codesign stripped from $i"
+        else
+            echo "Codesign couldn't be stripped from $i"
+        fi
+    fi
+    
     links=( $(otool -L Payload/*.app/Frameworks/"$i" | cut -d ' ' -f1) )
     for u in "${links[@]}"; do
-        for x in "${chain[@]}"; do
+        for x in "${inject[@]}"; do
             if [[ "$u" =~ "$x" ]]; then
                 install_name_tool -change "$u" @rpath/"$x" Payload/*.app/Frameworks/"$i"
+               
+                # VERBOSE
+                if [ -n "$v" ]; then
+                    if [ $? = 0 ]; then
+                        echo "Re-linked $u to @rpath/$x in $i"
+                    else
+                        echo "Re-link of $i failed"
+                    fi
+                fi
+                
                 break
             fi
         done
     done
 done
 
-if [ -z "$u" ]; then
+if [ -n "$u" ]; then
     plutil -remove UISupportedDevices Payload/*.app/Info.plist >> /dev/null
+
+    # VERBOSE ~~
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Removed UISupportedDevices from app"
+        else
+            echo "Couldn't remove UISupportedDevices from app"
+        fi
+    fi
 fi
 
-if [ ! -z "$v" ]; then
-    plutil -replace CFBundleVersion -string "$v" Payload/*.app/Info.plist >> /dev/null
-    plutil -replace CFBundleShortVersionString -string "$v" Payload/*.app/Info.plist >> /dev/null
+if [ -n "$c" ]; then
+    plutil -replace CFBundleVersion -string "$c" Payload/*.app/Info.plist >> /dev/null
+    
+    # VERBOSE ~~
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Changed CFBundleVersion to $c"
+        else
+            echo "Couldn't change CFBundleVersion to $c"
+        fi
+    fi
+    
+    plutil -replace CFBundleShortVersionString -string "$c" Payload/*.app/Info.plist >> /dev/null
+    
+    # VERBOSE ~~
+    if [ -n "$v" ]; then
+        if [ $? = 0 ]; then
+            echo "Changed CFBundleShortVersionString to $c"
+        else
+            echo "Couldn't change CFBundleShortVersionString to $c"
+        fi
+    fi
 fi
 
 # WRAPPING UP
 eval "zip -rqX '$output/$tweakname.ipa' Payload"
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ $? = 0 ]; then
+        echo "Generated IPA at "$output/$tweakname.ipa""
+    else
+        echo "Couldn't generate IPA"
+    fi
+fi
+
 rm -rf "$dir"
+
+# VERBOSE
+if [ -n "$v" ]; then
+    if [ $? = 0 ]; then
+        echo "Cleaned up"
+    else
+        echo "Couldn't clean up"
+    fi
+fi
